Table users as U {
  id bigserial [pk]
  hashed_password varchar(64) [not null]
  username varchar(64) [unique, not null]
  email varchar(255) [unique, not null]
  first_name varchar(255) [not null]
  last_name varchar(255) [not null]
  phone varchar(26) [not null]
  role varchar(255) [not null] // future enum
  created_at timestamptz [not null, default: `now()`]
  password_changed_at timestamptz [not null, default: '0001-01-01']
  updated_at timestamptz [not null, default: `now()`]

  Indexes {
      email [unique]
    }
}

Table accounts as A {
  id bigserial [pk]
  owner varchar(64) [ref: > U.username, not null]
  balance bigint [not null]
  currency varchar(3) [not null]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    owner
    (owner, currency) [unique]
  }
}

Table entries {
  id bigserial [pk]
  account_id bigint [ref: > A.id, not null]
  amount bigint [not null, note: 'can be negative or positive']
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    account_id
  }
}

Table transfers {
  id bigserial [pk]
  from_account_id bigint [ref: > A.id, not null]
  to_account_id bigint [ref: > A.id, not null]
  amount bigint [not null, note: 'must be positive']
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    from_account_id
    to_account_id
    (from_account_id, to_account_id)
  }
}

Table sessions {
  id uuid [pk]
  username varchar(64) [ref: > U.username, not null]
  refresh_token varchar [not null]
  user_agent varchar [not null]
  client_ip varchar(45) [not null]
  is_blocked boolean [not null, default: false]
  expires_at timestamptz [not null]
  created_at timestamptz [not null, default: `now()`]
}


Table product_categories {
  id bigserial [pk]
  name varchar(255) [unique, not null]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  // item_types ########
}

Table strains {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  name varchar(255) [not null, default: '']
  type varchar(255) [not null, default: ''] // future enum
  yield_average numeric(9,6)
  terp_average_total numeric(9,6)
  // change to individual terpenes
  terp_1 varchar(255)
  terp_1_value numeric(9,6)
  terp_2 varchar(255)
  terp_2_value numeric(9,6)
  terp_3 varchar(255)
  terp_3_value numeric(9,6)
  terp_4 varchar(255)
  terp_4_value numeric(9,6)
  terp_5 varchar(255)
  terp_5_value numeric(9,6)
  thc_average numeric(9,6)
  total_cannabinoid_average numeric(9,6)
  light_dep_2022 varchar [default: 'false'] // future enum
  fall_harvest_2022 varchar [default: 'false'] // future enum
  quantity_available numeric(9,6)
}

Table retailer_locations {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  name varchar(255) [not null, unique]
  address varchar(255) [not null]
  city varchar(255) [not null]
  state varchar(255) [not null]
  zip varchar(10) [not null]
  latitude numeric(9,6) [not null, default: 0.0]
  longitude numeric(9,6) [not null, default: 0.0]
  note varchar(1024)
  website varchar(2083)
  sells_flower boolean [default: false]
  sells_prerolls boolean [default: false]
  sells_pressed_hash boolean [default: false]
  created_by varchar(255)
}

Table items {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  description varchar(255) [not null, default: '']
  is_used boolean [not null, default: false]
  // packages #######
  item_type_id bigint [not null, ref: > item_types.id]
  strain_id bigint [not null, ref: > strains.id]
}

Table item_types {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  product_form varchar(255) [not null]
  product_modifier varchar(255) [not null]
  // items ######
  uom_default bigint [not null, ref: > uoms.id]
  product_category_id bigint [not null, ref: > product_categories.id]
}

Table package_tags {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  tag_number varchar(24) [not null]
  is_assigned boolean [not null, default: false]
  is_provisional boolean [not null, default: true]
  is_active boolean [not null, default: false]
  assigned_package_id bigint [ref: > packages.id]

  Indexes {
    tag_number [unique]
  }
}

Table packages {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  tag_id bigint [ref: > package_tags.id]
  package_type varchar(255) [not null] // future enum
  is_active boolean [not null, default: false]
  quantity numeric(9,6)
  notes varchar(1024)
  packaged_date_time timestamptz [not null, default: `now()`]
  harvest_date_time timestamptz
  lab_testing_state varchar(255) // future enum
  lab_testing_state_date_time timestamptz
  is_trade_sample boolean [not null, default: false]
  is_testing_sample boolean [not null, default: false]
  product_requires_remediation boolean [not null, default: false]
  contains_remediated_product boolean [not null, default: false]
  remediation_date_time timestamptz
  received_date_time timestamptz
  received_from_manifest_number varchar(255)
  received_from_facility_license_number varchar(255)
  received_from_facility_name varchar(255)
  is_on_hold boolean [not null, default: false]
  archived_date timestamptz
  finished_date timestamptz
  item_id bigint [ref: > items.id]
  // lab_tests ########
  // successor_packages #####
  // source_packages #####
  provisional_label varchar(255)
  is_provisional boolean [not null, default: false]
  is_sold boolean [not null, default: false]
  ppu_default numeric(19,4)
  ppu_on_order numeric(19,4)
  total_package_price_on_order numeric(19,4)
  ppu_sold_price numeric(19,4)
  total_sold_price numeric(19,4)
  packaging_supplies_consumed boolean [not null, default: false]
  is_line_item boolean [not null, default: false]
  order_id bigint [ref: > orders.id]
  uom_id bigint [ref: > uoms.id]

    Indexes {
        tag_id [unique]
    }
}

Table source_packages_child_packages {
  source_package_id bigint [ref: > packages.id]
  child_package_id bigint [ref: > packages.id]
}

Table lab_tests {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  test_name varchar(255) [not null, default: '']
  batch_code varchar(255) [not null, default: '']
  test_id_code varchar(255) [not null, default: '']
  lab_facility_name varchar(255) [not null, default: '']
  test_performed_date_time timestamptz [not null, default: `now()`]
  test_completed boolean [not null, default: false]
  overall_passed boolean [not null, default: false]
  test_type_name varchar(255) [not null, default: '']
  test_passed boolean [not null, default: false]
  test_comment varchar(255) [not null, default: '']
  thc_total_percent numeric(9,6)
  thc_total_value numeric(9,6)
  cbd_percent numeric(9,6)
  cbd_value numeric(9,6)
  terpene_total_percent numeric(9,6)
  terpene_total_value numeric(9,6)
  thc_a_percent numeric(9,6)
  thc_a_value numeric(9,6)
  delta9_thc_percent numeric(9,6)
  delta9_thc_value numeric(9,6)
  delta8_thc_percent numeric(9,6)
  delta8_thc_value numeric(9,6)
  thc_v_percent numeric(9,6)
  thc_v_value numeric(9,6)
  cbd_a_percent numeric(9,6)
  cbd_a_value numeric(9,6)
  cbn_percent numeric(9,6)
  cbn_value numeric(9,6)
  cbg_a_percent numeric(9,6)
  cbg_a_value numeric(9,6)
  cbg_percent numeric(9,6)
  cbg_value numeric(9,6)
  cbc_percent numeric(9,6)
  cbc_value numeric(9,6)
  total_cannabinoid_percent numeric(9,6)
  total_cannabinoid_value numeric(9,6)
}

Table lab_tests_packages {
  lab_test_id bigint [ref: > lab_tests.id]
  package_id bigint [ref: > packages.id]
}

Table uoms {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  name varchar(32) [not null]
  abbreviation varchar(16) [not null]
  // item_types
  // packages
}

Table orders {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  scheduled_pack_date_time timestamptz
  scheduled_ship_date_time timestamptz
  scheduled_delivery_date_time timestamptz
  actual_pack_date_time timestamptz
  actual_ship_date_time timestamptz
  actual_delivery_date_time timestamptz
  order_total numeric(19,4)
  notes varchar(1024)
  status varchar(255) [not null, default: ''] // future enum
  customer_name varchar(255) [not null, default: ''] // future customers model
  // line_item_packages ######
}

Table package_adjustments {
  id bigserial [pk]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  from_package_id bigint [ref: > packages.id, not null]
  to_package_id bigint [ref: > packages.id, not null]
  amount bigint [not null, note: 'must be positive']
  uom_id bigint [ref: > uoms.id, not null]

  Indexes {
    from_package_id
    to_package_id
    (from_package_id, to_package_id)
  }
}




